import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

const css = readFileSync(resolve(process.cwd(), "src/styles/app.css"), "utf8");

describe("professional graph styles", () => {
  it("defines responsive semantic graph and evidence inspector styling", () => {
    expect(css).toContain(".graph-toolbar {");
    expect(css).toContain("grid-template-columns: minmax(220px, 1fr)");
    expect(css).toContain(".semantic-node-table {");
    expect(css).toContain(".semantic-edge-foreign-key .react-flow__edge-path");
    expect(css).toContain(".react-flow__node.is-neighborhood .semantic-node");
    expect(css).toContain(".react-flow__node.is-dimmed .semantic-node");
    expect(css).toContain(".semantic-edge.is-neighborhood .react-flow__edge-path");
    expect(css).toContain(".semantic-edge.is-dimmed .react-flow__edge-path");
    expect(css).toContain(".graph-neighborhood-summary");
    expect(css).toContain(".pro-workbench .graph-neighborhood-summary");
    expect(css).toContain("top: 14px;");
    expect(css).toContain(".pro-workbench .react-flow__node.is-neighborhood .semantic-node");
    expect(css).toContain(".pro-workbench .semantic-edge.is-dimmed .react-flow__edge-path");
    expect(css).toContain(".graph-legend button");
    expect(css).toContain(".graph-legend button.is-muted");
    expect(css).toContain(".graph-legend button strong");
    expect(css).toContain(".graph-toolbar-actions .secondary-action");
    expect(css).toContain("max-width: min(280px, calc(100% - 28px));");
    expect(css).toContain(".pro-workbench .graph-legend button.active");
    expect(css).toContain(".pro-workbench .graph-legend button.is-muted strong");
    expect(css).toContain("max-width: min(300px, calc(100% - 250px));");
    expect(css).toContain("max-width: min(300px, calc(100% - 28px));");
    expect(css).toContain(".evidence-inspector {");
    expect(css).toContain("@media (max-width: 1100px)");
    expect(css).toContain(".workbench-shell {");
    expect(css).toContain(".workbench-header {");
    expect(css).toContain(".data-explorer-panel {");
    expect(css).toContain(".insight-panel {");
    expect(css).toContain(".workbench-status-bar {");
    expect(css).toContain(".workbench-shell.is-left-collapsed .workbench-main");
    expect(css).toContain(".workbench-shell.is-right-collapsed .workbench-main");
    expect(css).toContain("--gm-void: #06070b;");
    expect(css).toContain("--gm-panel: #10131b;");
    expect(css).toContain("--gm-accent: #24d3b5;");
    expect(css).toContain(".workbench-shell.pro-workbench.theme-light {");
    expect(css).toContain("--gm-void: #f4f7fb;");
    expect(css).toContain("--gm-panel: #ffffff;");
    expect(css).toContain("--gm-text: #172033;");
    expect(css).toContain("html[data-theme=\"light\"],");
    expect(css).toContain("body[data-theme=\"light\"] {");
    expect(css).toContain("color-scheme: light;");
    expect(css).toContain("html[data-theme=\"dark\"],");
    expect(css).toContain("color-scheme: dark;");
    expect(css).toContain(".pro-workbench.theme-light .data-explorer-panel,");
    expect(css).toContain(".pro-workbench.theme-light .command-palette {");
    expect(css).toContain(".pro-tree-panel.theme-light {");
    expect(css).toContain("accent-color: var(--gm-accent);");
    expect(css).toContain("html[data-theme=\"light\"] ::selection,");
    expect(css).toContain(".pro-workbench.theme-light .workbench-search input::placeholder,");
    expect(css).toContain(".pro-workbench.theme-light .command-palette-count,");
    expect(css).toContain(".pro-workbench.theme-light .chat-activity-item {");
    expect(css).toContain(".pro-tree-panel.theme-light .import-task-error {");
    expect(css).toContain(".workbench-shell.pro-workbench");
    expect(css).toContain(".pro-tree-panel");
    expect(css).toContain(".tree-row-field");
    expect(css).toContain(".insight-tabs");
    expect(css).toContain(".pro-workbench .insight-tab-panel {");
    expect(css).toContain(".graph-detail-overlay");
    expect(css).toContain(".graph-detail-evidence-metrics");
    expect(css).toContain(".react-flow__controls");
    expect(css).toContain(".react-flow__minimap");
    expect(css).toContain("--gm-left-width: clamp(228px, 17vw, 292px);");
    expect(css).toContain("--gm-right-width: clamp(286px, 22vw, 360px);");
    expect(css).toContain("--gm-collapsed-left-width: 44px;");
    expect(css).toContain("--gm-collapsed-right-width: 44px;");
    expect(css).toContain("--gm-header-height: 60px;");
    expect(css).toContain("--gm-status-height: 28px;");
    expect(css).toContain(".pro-workbench .workbench-main {");
    expect(css).toContain("grid-template-columns: var(--gm-left-width) minmax(0, 1fr) var(--gm-right-width);");
    expect(css).toContain("grid-template-columns: var(--gm-left-width) minmax(0, 1fr) var(--gm-collapsed-right-width);");
    expect(css).toContain("@media (max-width: 1080px)");
    expect(css).toContain(".pro-workbench .graph-toolbar {");
    expect(css).toContain("position: static;");
    expect(css).toContain("z-index: 8;");
    expect(css).toContain(".graph-analysis-toggle");
    expect(css).toContain(".graph-analysis-drawer");
    expect(css).toContain(".graph-analysis-drawer-body");
    expect(css).toContain(".pro-workbench .edge-summary {");
    expect(css).toContain(".edge-summary-group {");
    expect(css).toContain(".edge-summary-empty");
    expect(css).toContain(".pro-workbench .edge-summary-empty");
    expect(css).toContain(".edge-summary-group-heading {");
    expect(css).toContain(".edge-summary-cards {");
    expect(css).toContain(".edge-summary-card span");
    expect(css).toContain(".edge-summary-card small");
    expect(css).toContain(".edge-summary-card.is-previewed");
    expect(css).toContain(".edge-summary-card.is-neighborhood");
    expect(css).toContain(".edge-summary-card.is-dimmed");
    expect(css).toContain(".pro-workbench .edge-summary-card.is-previewed");
    expect(css).toContain(".pro-workbench .edge-summary-card.is-neighborhood");
    expect(css).toContain(".pro-workbench .graph-analysis-drawer {");
    expect(css).toContain("top: calc(var(--gm-graph-heading-height) + 10px);");
    expect(css).toContain("width: min(420px, calc(100% - 28px));");
    expect(css).toContain("position: static;");
    expect(css).toContain("max-height: none;");
    expect(css).toContain(".pro-workbench .graph-canvas {");
    expect(css).toContain("min-height: clamp(340px, calc(100vh - 180px), 744px);");
    expect(css).toContain(".pro-workbench .react-flow__minimap {");
    expect(css).toContain(".pro-workbench .react-flow__minimap-mask {");
    expect(css).toContain(".app-shell {");
    expect(css).toContain("height: 100vh;");
    expect(css).toContain(".workbench-shell.pro-workbench {");
    expect(css).toContain("overflow: hidden;");
    expect(css).toContain(".pro-workbench .data-explorer-panel {");
    expect(css).toContain("grid-template-rows: auto minmax(0, 1fr);");
    expect(css).toContain(".pro-tree-panel .resource-tree {");
    expect(css).toContain("overflow-y: auto;");
    expect(css).toContain("overflow-x: hidden;");
    expect(css).toContain(".pro-tree-panel .tree-row {");
    expect(css).toContain(".panel-heading-actions {");
    expect(css).toContain(".data-actions-backdrop {");
    expect(css).toContain(".data-actions-dialog {");
    expect(css).toContain("place-items: start end;");
    expect(css).toContain("width: min(430px, calc(100vw - 36px));");
    expect(css).toContain(".data-actions-dialog header .panel-icon-button {");
    expect(css).toContain("background: var(--gm-elevated);");
    expect(css).toContain(".data-actions-dialog.pro-tree-panel .panel.intake-panel {");
    expect(css).toContain("overflow-y: auto;");
    expect(css).toContain(".upload-box input {");
    expect(css).toContain("opacity: 0;");
    expect(css).toContain(".import-action-row {");
    expect(css).toContain(".import-wizard {");
    expect(css).toContain(".import-wizard-step {");
    expect(css).toContain(".pro-tree-panel .import-wizard-step {");
    expect(css).toContain(".import-summary-metrics {");
    expect(css).toContain(".pro-tree-panel .import-summary-card {");
    expect(css).toContain(".field-mapping-card,\n.relationship-modeling-card {");
    expect(css).toContain(".field-profile-row,\n.relationship-candidate-row {");
    expect(css).toContain(".pro-tree-panel .field-profile-list,\n.pro-tree-panel .relationship-candidate-list {");
    expect(css).toContain(".relationship-candidate-controls,\n.relationship-rule-controls {");
    expect(css).toContain(".relationship-rule-panel {");
    expect(css).toContain(".relationship-merge-list button {");
    expect(css).toContain("max-height: 220px;");
    expect(css).toContain("max-height: 260px;");
    expect(css).toContain(".pro-tree-panel .profile-summary-empty p {");
    expect(css).toContain("-webkit-line-clamp: 2;");
  });

  it("guards productized responsive workbench layout against panel and overlay collisions", () => {
    expect(css).toContain("--gm-left-width: clamp(228px, 17vw, 292px);");
    expect(css).toContain("--gm-right-width: clamp(286px, 22vw, 360px);");
    expect(css).toContain("grid-template-columns: var(--gm-left-width) minmax(0, 1fr) var(--gm-right-width);");
    expect(css).toContain("grid-template-rows: var(--gm-header-height) auto auto minmax(0, 1fr) var(--gm-status-height);");
    expect(css).toContain("grid-template-rows: auto auto auto minmax(0, 1fr) var(--gm-status-height);");
    expect(css).toContain("grid-template-rows: auto auto auto minmax(0, 1fr) 30px;");
    expect(css).toContain(".pro-workbench .workbench-next-step {");
    expect(css).toContain(".pro-workbench .graph-panel {");
    expect(css).toContain("display: grid;");
    expect(css).toContain("grid-template-rows: auto minmax(0, 1fr);");
    expect(css).toContain("padding-top: 6px;");
    expect(css).toContain("border-top: 1px solid var(--gm-border-soft);");
    expect(css).toContain(".pro-workbench .graph-panel.is-tools-open {");
    expect(css).toContain("grid-template-rows: auto minmax(0, 1fr);");
    expect(css).toContain(".graph-tools-toggle");
    expect(css).toContain(".graph-tools-drawer");
    expect(css).toContain("top: calc(var(--gm-graph-heading-height) + 8px);");
    expect(css).toContain("max-height: min(56vh, 420px);");
    expect(css).toContain(".pro-workbench .graph-heading {");
    expect(css).toContain("grid-template-columns: minmax(0, 1fr) auto;");
    expect(css).toContain(".pro-workbench .graph-heading-main {");
    expect(css).toContain(".pro-workbench .graph-heading-metrics {");
    expect(css).toContain("grid-template-columns: repeat(3, minmax(0, auto));");
    expect(css).toContain(".pro-workbench .graph-heading-metrics span {");
    expect(css).toContain(".pro-workbench.theme-light .graph-heading-metrics span,");
    expect(css).toContain(".pro-workbench .graph-heading-actions {");
    expect(css).toContain("flex-wrap: wrap;");
    expect(css).toContain("max-width: min(292px, 36vw);");
    expect(css).toContain(".pro-workbench .graph-toolbar-actions .icon-action");
    expect(css).toContain("width: 32px;");
    expect(css).toContain("height: 32px;");
    expect(css).toContain("clip: rect(0 0 0 0);");
    expect(css).toContain(".pro-workbench .graph-canvas {");
    expect(css).toContain("min-height: clamp(340px, calc(100vh - 180px), 744px);");
    expect(css).toContain(".pro-workbench .graph-toolbar {");
    expect(css).toContain("position: static;");
    expect(css).toContain("grid-template-columns: repeat(auto-fit, minmax(min(100%, 216px), 1fr));");
    expect(css).toContain(".pro-workbench .graph-filter-card {");
    expect(css).toContain(".pro-workbench .graph-filter-card-view {");
    expect(css).toContain("min-width: min(100%, 232px);");
    expect(css).toContain(".pro-workbench .graph-filter-card-layout {");
    expect(css).toContain(".pro-workbench .graph-filter-card-snapshots {");
    expect(css).toContain(".pro-workbench .graph-preset-actions {");
    expect(css).toContain(".pro-workbench .graph-snapshot-list {");
    expect(css).toContain(".pro-workbench .graph-workflow-strip {");
    expect(css).toContain(".pro-workbench .filter-chip-grid {");
    expect(css).toContain("grid-template-columns: repeat(auto-fit, minmax(74px, 1fr));");
    expect(css).toContain(".pro-workbench .filter-chip.active {");
    expect(css).toContain(".pro-workbench .edge-summary {");
    expect(css).toContain(".pro-workbench .graph-analysis-drawer {");
    expect(css).toContain("position: absolute;");
    expect(css).toContain("top: calc(var(--gm-graph-heading-height) + 10px);");
    expect(css).toContain("box-sizing: border-box;");
    expect(css).toContain("width: min(420px, calc(100% - 28px));");
    expect(css).toContain(".pro-workbench .graph-neighborhood-summary,");
    expect(css).toContain(".pro-workbench .graph-ai-path-summary,");
    expect(css).toContain(".pro-workbench .graph-path-analysis-summary {");
    expect(css).toContain("position: static;");
    expect(css).toContain("max-height: none;");
    expect(css).toContain("overflow: auto;");
    expect(css).toContain(".pro-workbench .graph-legend {");
    expect(css).toContain(".pro-workbench .graph-legend.is-compact {");
    expect(css).toContain("grid-template-columns: repeat(4, minmax(0, 1fr));");
    expect(css).toContain("max-width: min(360px, calc(100% - 236px));");
    expect(css).toContain(".pro-workbench .graph-legend.is-compact button {");
    expect(css).toContain(".pro-workbench .graph-legend.is-compact span {");
    expect(css).toContain("clip: rect(0 0 0 0);");
    expect(css).toContain("transition: border-color 180ms ease, background 180ms ease, color 180ms ease;");
    expect(css).toContain(".pro-workbench .chat-panel {");
    expect(css).toContain(".pro-workbench .chat-panel-header {");
    expect(css).toContain("grid-template-columns: minmax(0, 1fr) auto;");
    expect(css).toContain(".pro-workbench .chat-panel-header .ai-mode-note {");
    expect(css).toContain(".pro-workbench .chat-panel-body-label {");
    expect(css).toContain("flex-direction: column;");
    expect(css).toContain("flex: 1 1 auto;");
    expect(css).toContain(".pro-workbench .chat-panel h2 {");
    expect(css).toContain("margin: 0 0 8px;");
    expect(css).toContain(".pro-workbench .chat-form {");
    expect(css).toContain("flex: 0 0 auto;");
    expect(css).toContain(".pro-workbench .chat-form textarea {");
    expect(css).toContain("min-height: 54px;");
    expect(css).toContain("grid-template-columns: minmax(0, 1fr) auto;");
    expect(css).toContain(".ai-status-summary");
    expect(css).toContain("grid-template-columns: repeat(2, minmax(0, 1fr));");
    expect(css).toContain(".ai-status-actions");
    expect(css).toContain(".pro-workbench .chat-messages,");
    expect(css).toContain(".pro-workbench .review-card-list,");
    expect(css).toContain(".pro-workbench .evidence-inspector {");
    expect(css).toContain("@media (max-width: 1280px)");
    expect(css).toContain("grid-template-columns: repeat(3, minmax(0, 1fr));");
    expect(css).toContain("grid-template-columns: minmax(204px, 0.24fr) minmax(0, 1fr) minmax(250px, 0.28fr);");
    expect(css).toContain("@media (max-width: 1180px) and (min-width: 1081px)");
    expect(css).toContain("grid-template-columns: minmax(188px, 0.2fr) minmax(0, 1fr) minmax(232px, 0.24fr);");
    expect(css).toContain(".pro-workbench.is-right-collapsed .workbench-main {");
    expect(css).toContain(".pro-workbench.is-graph-focus .workbench-main {");
    expect(css).toContain(".pro-workbench .insight-panel {");
    expect(css).toContain(".pro-workbench .insight-panel.is-collapsed {");
    expect(css).toContain("place-items: start center;");
    expect(css).toContain(".pro-workbench .insight-panel.is-collapsed button {");
    expect(css).toContain("grid-column: 1 / -1;");
    expect(css).toContain("@media (max-height: 820px) and (min-width: 1081px)");
    expect(css).toContain("grid-template-columns: minmax(188px, 0.2fr) minmax(0, 1fr) minmax(272px, 0.26fr);");
    expect(css).toContain(".pro-workbench .chat-messages {");
    expect(css).toContain("min-height: clamp(168px, 24vh, 260px);");
    expect(css).toContain("grid-template-columns: 1fr;");
    expect(css).toContain("max-height: 72px;");
    expect(css).toContain("display: none;");
    expect(css).toContain("min-height: 46px;");
    expect(css).toContain("@media (max-height: 760px)");
    expect(css).toContain("max-height: min(62vh, 380px);");
    expect(css).toContain("max-height: none;");
    expect(css).toContain(".pro-workbench .graph-analysis-drawer {");
    expect(css).toContain("max-height: calc(100% - var(--gm-graph-heading-height) - 18px);");
    expect(css).toContain("@media (max-width: 1080px)");
    expect(css).toContain("grid-template-columns: minmax(0, 1fr);");
    expect(css).toContain("order: 1;");
    expect(css).toContain("min-height: min(76vh, 780px);");
    expect(css).toContain("max-height: calc(100% - var(--gm-graph-heading-height) - 22px);");
    expect(css).toContain("order: 2;");
    expect(css).toContain("order: 3;");
    expect(css).toContain(".pro-workbench.is-graph-focus .graph-panel {");
    expect(css).toContain("max-height: min(34vh, 320px);");
    expect(css).toContain("@media (max-width: 640px)");
    expect(css).toContain("grid-template-columns: minmax(0, 1fr) auto;");
    expect(css).toContain("padding: 10px 124px 10px 10px;");
    expect(css).toContain("box-sizing: border-box;");
    expect(css).toContain("width: 100vw;");
    expect(css).toContain("max-width: 100vw;");
    expect(css).toContain("width: 100%;");
    expect(css).toContain("max-width: 100%;");
    expect(css).toContain("overflow-x: hidden;");
    expect(css).toContain("max-height: min(58vh, 360px);");
    expect(css).toContain(".pro-workbench .graph-analysis-drawer {");
    expect(css).toContain("max-height: min(58vh, 430px);");
    expect(css).toContain(".pro-workbench .react-flow__minimap {\n    display: none;\n  }");
    expect(css).toContain(".pro-workbench .edge-summary-group {");
    expect(css).toContain("min-width: min(260px, calc(100vw - 44px));");
    expect(css).toContain(".pro-workbench .edge-summary-cards {");
    expect(css).toContain("overflow-x: auto;");
    expect(css).toContain("flex-wrap: nowrap;");
    expect(css).toContain(".pro-workbench .edge-summary-card {");
    expect(css).toContain("min-width: 170px;");
    expect(css).toContain("max-width: 190px;");
    expect(css).toContain(".pro-workbench .edge-summary-more {");
    expect(css).toContain("min-width: max-content;");

    expect(css).toContain(".pro-workbench .filter-chip-grid,");
    expect(css).toContain(".pro-workbench .filter-chip-grid.compact {");
    expect(css).toContain("grid-template-columns: repeat(2, minmax(0, 1fr));");
    expect(css).toContain("grid-template-columns: repeat(4, minmax(0, 1fr));");
    expect(css).toContain("left: 10px;");
    expect(css).toContain("right: 10px;");
    expect(css).toContain("width: auto;");
    expect(css).toContain(".workbench-status-metrics {");
    expect(css).toContain(".workbench-status-context {");
    expect(css).toContain(".workbench-status-full {");
    expect(css).toContain(".workbench-status-value,");
    expect(css).toContain(".workbench-status-label {");
    expect(css).toContain(".pro-workbench .ai-status-strip {");
    expect(css).toContain("grid-template-columns: minmax(0, 1fr);");
    expect(css).toContain(".pro-workbench .ai-status-actions {");
    expect(css).toContain("grid-template-columns: repeat(2, minmax(0, 1fr));");
    expect(css).toContain(".pro-workbench .graph-legend button span {");
  });

  it("keeps dark data import dialog cards on themed surfaces", () => {
    expect(css).toContain(".pro-tree-panel .first-graph-template button {");
    expect(css).toContain(".pro-tree-panel .first-graph-template-guidance {");
    expect(css).toContain(".pro-tree-panel .first-graph-template-preset {");
    expect(css).toContain(".pro-tree-panel .import-help-panel {");
    expect(css).toContain(".pro-tree-panel .import-help-topic {");
    expect(css).toContain(".pro-tree-panel .import-help-search input {");
    expect(css).toContain(".pro-tree-panel .import-help-action {");
    expect(css).toContain(".pro-tree-panel .import-task-stage {");
    expect(css).toContain(".pro-tree-panel .import-task-diagnostics li {");
    expect(css).toContain(".pro-tree-panel .import-task-recovery {");
    expect(css).toContain(".pro-tree-panel .import-task-recovery-detail code {");
    expect(css).toContain("background: rgba(16, 19, 27, 0.58);");
    expect(css).toContain("background: rgba(7, 10, 16, 0.48);");
    expect(css).toContain(".pro-tree-panel.theme-light .import-help-panel,");
  });

  it("keeps production chrome usable on narrow viewports", () => {
    expect(css).toContain(".pro-workbench .workbench-header {");
    expect(css).toContain("grid-template-columns: minmax(170px, 0.64fr) minmax(260px, 0.8fr) minmax(112px, auto) auto;");
    expect(css).toContain("height: var(--gm-header-height);");
    expect(css).toContain(".pro-workbench .workbench-module-tabs {");
    expect(css).toContain("grid-row: 1;");
    expect(css).toContain("grid-template-columns: repeat(3, minmax(0, 1fr));");
    expect(css).toContain(".pro-workbench .workbench-header-action {");
    expect(css).toContain(".pro-workbench .workbench-module-context {");
    expect(css).toContain(".workbench-header-actions {");
    expect(css).toContain("justify-self: end;");
    expect(css).toContain(".workbench-search-toggle,");
    expect(css).toContain(".workbench-search-close {");
    expect(css).toContain(".pro-workbench .language-switcher {");
    expect(css).toContain(".pro-workbench .workbench-brand h1,");
    expect(css).toContain(".pro-workbench .workbench-brand p {");
    expect(css).toContain("text-overflow: ellipsis;");
    expect(css).toContain(".workbench-search {");
    expect(css).toContain("position: absolute;");
    expect(css).toContain("width: min(420px, calc(100vw - 32px));");
    expect(css).toContain(".pro-workbench .workbench-status-bar {");
    expect(css).toContain("overflow: hidden;");
    expect(css).toContain("grid-template-columns: minmax(0, 1fr) 34px;");
    expect(css).toContain(".workbench-status-context {");
    expect(css).toContain("display: none;");
    expect(css).toContain(".ai-settings-panel {");
    expect(css).toContain("display: grid;");
    expect(css).toContain("grid-template-rows: auto minmax(0, 1fr);");
    expect(css).toContain(".ai-settings-panel form {");
    expect(css).toContain("grid-template-rows: minmax(0, 1fr) auto auto;");
    expect(css).toContain(".ai-settings-fields {");
    expect(css).toContain("overflow-y: auto;");
    expect(css).toContain(".ai-settings-panel footer {");
    expect(css).toContain("position: sticky;");
    expect(css).toContain("bottom: 0;");
    expect(css).toContain("@media (max-width: 1280px)");
    expect(css).toContain("grid-template-columns: minmax(170px, 0.62fr) minmax(248px, 0.8fr) auto;");
    expect(css).toContain("grid-column: 3;");
    expect(css).toContain("@media (max-width: 1080px)");
    expect(css).toContain("grid-template-rows: auto auto auto minmax(0, 1fr) var(--gm-status-height);");
    expect(css).toContain("grid-template-columns: minmax(0, 1fr) auto;");
    expect(css).toContain("grid-template-rows: auto auto;");
    expect(css).toContain("min-height: 96px;");
    expect(css).toContain("@media (max-height: 760px) and (max-width: 1080px)");
    expect(css).toContain("min-height: min(72vh, 640px);");
    expect(css).toContain("height: 100%;");
    expect(css).toContain("min-height: 0;");
    expect(css).toContain("max-height: 100%;");
    expect(css).toContain("max-height: calc(100vh - 40px);");
    expect(css).toContain(".pro-workbench.is-module-data .graph-panel,");
    expect(css).toContain(".pro-workbench.is-module-insights .data-explorer-panel,");
    expect(css).toContain(".pro-workbench.is-module-graph .data-explorer-panel,");
    expect(css).toContain(".pro-workbench.is-module-data .data-explorer-panel,");
    expect(css).toContain("min-height: min(76vh, 780px);");
    expect(css).toContain(".pro-workbench .workbench-search-results {");
    expect(css).toContain("max-height: min(42vh, 320px);");
    expect(css).toContain("@media (max-width: 640px)");
    expect(css).toContain(".pro-workbench .language-switcher {");
    expect(css).toContain("display: none;");
    expect(css).toContain("grid-template-columns: minmax(0, 1fr) auto;");
    expect(css).toContain("grid-template-columns: repeat(5, 34px);");
    expect(css).toContain("padding-right: 188px;");
    expect(css).toContain(".pro-workbench .graph-canvas {\n    height: 100%;\n    min-height: 210px;");
    expect(css).toContain(".command-palette-backdrop {");
    expect(css).toContain(".command-palette {");
    expect(css).toContain(".command-palette {\n  box-sizing: border-box;");
    expect(css).toContain(".command-palette-option {");
    expect(css).toContain(".pro-workbench .workbench-header-actions .workbench-header-action,");
    expect(css).toContain(".pro-workbench .workbench-search-toggle {");
    expect(css).toContain("position: static;");
    expect(css).toContain("max-height: min(34vh, 240px);");
    expect(css).toContain(".pro-workbench .workbench-search-results {\n    max-height: min(22vh, 150px);");
    expect(css).toContain(".pro-workbench .workbench-search-results button {\n    grid-template-columns: 58px minmax(0, 1fr);");
    expect(css).toContain(".ai-settings-backdrop {");
    expect(css).toContain("padding: 10px;");
    expect(css).toContain("@media (max-width: 640px) and (max-height: 720px)");
    expect(css).toContain(".pro-workbench.is-module-insights .insight-panel {");
    expect(css).toContain(".pro-workbench .ai-status-card small + small,");
    expect(css).toContain(".pro-workbench.is-module-insights .chat-panel-header .ai-mode-note,");
    expect(css).toContain(".pro-workbench .chat-empty-state {");
    expect(css).toContain(".pro-workbench.is-module-insights .chat-messages {\n    flex: 0 0 112px;");
    expect(css).toContain("grid-template-columns: minmax(0, 1fr) auto;");
    expect(css).toContain("grid-template-rows: auto auto;");
    expect(css).toContain(".pro-workbench .chat-form textarea {\n    grid-column: 1;");
    expect(css).toContain("min-height: 42px;");
    expect(css).toContain("box-sizing: border-box;");
    expect(css).toContain("grid-row: 2;");
    expect(css).toContain(".pro-workbench .chat-form button {\n    grid-column: 2;");
    expect(css).toContain("grid-row: 2;");
    expect(css).toContain("min-height: 42px;");
    expect(css).toContain(".pro-workbench .workbench-search {\n    max-height: min(28vh, 190px);");
    expect(css).toContain(".pro-workbench .workbench-search-results {\n    max-height: min(16vh, 108px);");
    expect(css).toContain(".pro-workbench .graph-tools-drawer {\n    max-height: min(48vh, 300px);");
  });
});
